### ISSUE TITLE
Possibilité de monitorer plusieurs JVM sur un serveur

### ISSUE THREAD

**Issue by pmioulet** [btravers/Back#10]
Sur un même serveur on peut faire tourner plusieurs applications Java toutes monitorables via JMX avec des ports différents.

Actuellement il manque un moyen de faire ca puisque la clé pour un serveur est seulement sur le hostname et non sur le couple hostname:port

**Comment by btravers** [comment]
Commit 7a8f42df0a3ecd81f4c8a6aeacd74c5e15a38c7a
