### ISSUE TITLE
Gestion des erreurs côté client

### ISSUE THREAD

**Issue by pmioulet** [btravers/Back#2]
Actuellement, si une requête vers le serveur échoue, l'utilisateur n'a aucune information pour le savoir, il faut aller voir les logs sur le serveur pour s'en rendre compte, il faudrait au moins mettre une info bulle d'erreur sur l'écran pour le prévenir (upload+ edition/visualisation de serveur)

**Comment by btravers** [comment]
Si une erreur arrive après la validation d'un document, un bad request est générée et les champs invalides sont tagués dans le formulaire.
Si une erreur a lieu autrement, un internal error est généré et affiché dans des bulles en haut de la page html.
