### ISSUE TITLE
Upload crée plusieurs serveurs

### ISSUE THREAD

**Issue by pmioulet** [btravers/Back#5]
Sur l'upload du fichier d'un serveur nommé agrhsoa0.mondomaine.com, j'ai eu 2 serveurs de créé au lieu d'un:
![image](https://cloud.githubusercontent.com/assets/3446555/7229377/3b044de2-e763-11e4-87fa-733bec719b08.png)

Le mapping contient
 "hostName": {
                  "type": "string",
                  "index": "not_analyzed"
               },

Alors que les objets et l'aggrégation se fait sur host, un lien p-e :)

**Comment by btravers** [comment]
Problème résolu après le merges de branches.
