### ISSUE TITLE
Tronquer le titre s'il est trop long pour pouvoir afficher titre+icones 

### ISSUE THREAD

**Issue by pmioulet** [btravers/Back#9]
Tronquer le titre s'il est trop long pour pouvoir afficher titre+icones 
+ Ajouter l'affichage du nom complet si on passe la souris au dessus du titre

![image](https://cloud.githubusercontent.com/assets/3446555/7231100/653f9174-e773-11e4-96eb-1c98b486bc8a.png)

**Comment by mathieu-pousse** [comment]
franchement ca serait plus simple de mttre des noms plus court...

**Comment by pmioulet** [comment]
Depuis quand t'es expert UX toi :p

**Comment by btravers** [comment]
Done
